// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK7PvtW4OZCYNq_nnl-RO-T46ForXLs1k',
    appId: '1:165407103652:web:37608f47e7352701cf2431',
    messagingSenderId: '165407103652',
    projectId: 'sinflix-217cc',
    authDomain: 'sinflix-217cc.firebaseapp.com',
    storageBucket: 'sinflix-217cc.firebasestorage.app',
    measurementId: 'G-0G4Q5981CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx-2lC7VkxutgEbvEvRHS0I4qXVOwP5K0',
    appId: '1:165407103652:android:c2e1285eed8d2508cf2431',
    messagingSenderId: '165407103652',
    projectId: 'sinflix-217cc',
    storageBucket: 'sinflix-217cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKl8_72jcgRrx6IHrl_nhSw9TCvTH7mfA',
    appId: '1:165407103652:ios:22f894fb40717079cf2431',
    messagingSenderId: '165407103652',
    projectId: 'sinflix-217cc',
    storageBucket: 'sinflix-217cc.firebasestorage.app',
    iosBundleId: 'com.berkeozkul.sinflix.sinflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK7PvtW4OZCYNq_nnl-RO-T46ForXLs1k',
    appId: '1:165407103652:web:774dd854a1a3c4adcf2431',
    messagingSenderId: '165407103652',
    projectId: 'sinflix-217cc',
    authDomain: 'sinflix-217cc.firebaseapp.com',
    storageBucket: 'sinflix-217cc.firebasestorage.app',
    measurementId: 'G-TLNQHT593E',
  );
}
